import time
from typing import Any

from langchain_openai import ChatOpenAI

from agents.state import AgentState

SYSTEM_PROMPT = """You are a Writer Agent. Your job is to synthesize all research and analysis into a polished, professional report.

Produce a well-structured report with these exact sections:

# [Report Title]

## Executive Summary
[2-3 paragraph overview of the most important findings]

## Key Findings
[Bulleted list of 5-7 most important discoveries]

## Analysis
[Detailed analysis covering patterns, trends, and context]

## Risks & Challenges
[Honest assessment of risks and challenges]

## Recommendations
[3-5 actionable, specific recommendations]

## Conclusion
[Brief closing paragraph]

---
*Report generated by AutoCrew Multi-Agent Research Platform*

Write in a professional, clear style. Be specific and data-driven. Avoid vague language."""

llm = ChatOpenAI(model="gpt-4o", temperature=0.3)


async def writer_node(state: AgentState) -> dict[str, Any]:
    """Synthesize all findings into a polished final report."""
    start_time = time.time()

    statuses = dict(state.get("agent_statuses", {}))
    statuses["writer"] = "running"
    metadata = dict(state.get("metadata", {}))

    try:
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": (
                    f"Original research task: {state['input_task']}\n\n"
                    f"Research plan:\n{state['manager_plan']}\n\n"
                    f"Research findings:\n{state['research_results']}\n\n"
                    f"Analysis:\n{state['analysis_results']}"
                ),
            },
        ]

        response = await llm.ainvoke(messages)
        final_output = response.content

        tokens = response.usage_metadata or {}
        metadata["writer_tokens"] = tokens.get("total_tokens", 0)
        metadata["writer_duration_ms"] = int((time.time() - start_time) * 1000)
        metadata.setdefault("total_tokens", 0)
        metadata["total_tokens"] += metadata["writer_tokens"]
        metadata["total_duration_ms"] = (
            metadata.get("manager_duration_ms", 0)
            + metadata.get("research_duration_ms", 0)
            + metadata.get("analyst_duration_ms", 0)
            + metadata["writer_duration_ms"]
        )

        statuses["writer"] = "done"

        return {
            "final_output": final_output,
            "current_agent": "writer",
            "agent_statuses": statuses,
            "metadata": metadata,
            "error": None,
        }

    except Exception as e:
        statuses["writer"] = "error"
        return {
            "current_agent": "writer",
            "agent_statuses": statuses,
            "metadata": metadata,
            "error": str(e),
        }
